"use client";

import Link from "next/link";
import { PaymentQuote } from "@/lib/booking/payment";

interface Props {
  payment: PaymentQuote;
  onBack: () => void;
  onPay?: () => void;
}

export default function PaymentSummary({
  payment,
  onBack,
  onPay,
}: Props) {
  const {
    bookingId,
    bookingType,
    title,
    customerName,
    mobile,
    email,
    workflowStatus,
    originalAmount,
    discount,
    finalAmount,
    paymentLink,
  } = payment;

  const renderStatus = () => {
    switch (workflowStatus) {
      case "PENDING_REVIEW":
        return (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4">
            <h3 className="font-semibold text-amber-700">
              Booking Submitted Successfully
            </h3>

            <p className="mt-2 text-sm text-gray-700">
              Your request has been received by the SHIFA LIFE LINE Operations
              Team.
            </p>

            <ul className="mt-4 list-disc space-y-1 pl-5 text-sm text-gray-600">
              <li>Diagnostic requests will be reviewed for the best offers.</li>
              <li>Pharmacy requests will undergo stock verification.</li>
              <li>A final quotation will be prepared.</li>
              <li>
                A secure payment link will be shared after confirmation.
              </li>
            </ul>
          </div>
        );

      case "QUOTE_READY":
        return (
          <div className="rounded-lg border border-blue-200 bg-blue-50 p-4">
            <h3 className="font-semibold text-blue-700">
              Quotation Ready
            </h3>

            <div className="mt-4 space-y-2 text-sm">
              {originalAmount !== undefined && (
                <div className="flex justify-between">
                  <span>Original Price</span>
                  <span>₹{originalAmount.toFixed(2)}</span>
                </div>
              )}

              {discount !== undefined && (
                <div className="flex justify-between text-green-600">
                  <span>Discount</span>
                  <span>- ₹{discount.toFixed(2)}</span>
                </div>
              )}

              <div className="flex justify-between border-t pt-2 font-bold">
                <span>Final Amount</span>
                <span>₹{(finalAmount ?? 0).toFixed(2)}</span>
              </div>
            </div>

            <p className="mt-4 text-sm text-gray-600">
              Your quotation has been prepared. Payment link will be enabled
              once generated by the Operations Team.
            </p>
          </div>
        );

      case "PAYMENT_PENDING":
        return (
          <div className="rounded-lg border border-green-200 bg-green-50 p-4">
            <h3 className="font-semibold text-green-700">
              Payment Link Ready
            </h3>

            <div className="mt-4 space-y-2 text-sm">
              {originalAmount !== undefined && (
                <div className="flex justify-between">
                  <span>Original Price</span>
                  <span>₹{originalAmount.toFixed(2)}</span>
                </div>
              )}

              {discount !== undefined && (
                <div className="flex justify-between text-green-600">
                  <span>Discount</span>
                  <span>- ₹{discount.toFixed(2)}</span>
                </div>
              )}

              <div className="flex justify-between border-t pt-2 font-bold">
                <span>Amount Payable</span>
                <span>₹{(finalAmount ?? 0).toFixed(2)}</span>
              </div>
            </div>

            <div className="mt-6 flex gap-3">
              {paymentLink && (
                <Link
                  href={paymentLink}
                  className="rounded-lg bg-blue-600 px-4 py-2 text-white transition hover:bg-blue-700"
                >
                  Open Payment Link
                </Link>
              )}

              {onPay && (
                <button
                  onClick={onPay}
                  className="rounded-lg bg-green-600 px-4 py-2 text-white transition hover:bg-green-700"
                >
                  Proceed to Payment
                </button>
              )}
            </div>
          </div>
        );

      case "PAYMENT_RECEIVED":
        return (
          <div className="rounded-lg border border-emerald-300 bg-emerald-50 p-4">
            <h3 className="font-semibold text-emerald-700">
              Payment Successful
            </h3>

            <p className="mt-2 text-sm text-gray-700">
              Thank you. Your payment has been received successfully.
            </p>

            <p className="mt-2 text-sm text-gray-700">
              Our team will now proceed with scheduling and service fulfilment.
            </p>
          </div>
        );

      default:
        return null;
    }
  };

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <h2 className="text-3xl font-bold">
        Payment & Booking Summary
      </h2>

      <div className="rounded-xl border bg-white p-6 shadow-sm">
        <div className="grid gap-3 sm:grid-cols-2">
          <div>
            <span className="font-semibold">Booking Reference</span>
            <p>{bookingId}</p>
          </div>

          <div>
            <span className="font-semibold">Booking Type</span>
            <p>{bookingType}</p>
          </div>

          <div>
            <span className="font-semibold">Service</span>
            <p>{title}</p>
          </div>

          <div>
            <span className="font-semibold">Customer</span>
            <p>{customerName}</p>
          </div>

          <div>
            <span className="font-semibold">Mobile</span>
            <p>{mobile}</p>
          </div>

          {email && (
            <div>
              <span className="font-semibold">Email</span>
              <p>{email}</p>
            </div>
          )}
        </div>
      </div>

      {renderStatus()}

      <div className="flex justify-end">
        <button
          onClick={onBack}
          className="rounded-lg border px-5 py-2 hover:bg-gray-100"
        >
          Back
        </button>
      </div>
    </div>
  );
}