export const DOCTORS = [
  {
    id: 1,
    name: "Dr. Ritun Sarkar",
    qualification: "MBBS, MD (Medicine)",
    speciality: "General Medicine, Female Health & Wellbeing",
    experience: "",
    branch: "",
    image: "/doctors/dr-ritun-sarkar.png",
  },
  {
    id: 2,
    name: "Dr. Asish Debnath",
    qualification: "MBBS, DA, DCH, MD (Psychiatry)",
    speciality: "Neuro Psychiatrist, Mental Health, De-Addiction Specialist",
    experience: "",
    branch: "",
    image: "/doctors/dr-asish-debnath.png",
  },
  {
    id: 3,
    name: "Dr. Sibasish Mukherjee",
    qualification: "MBBS, DNB (Nephrology)",
    speciality: "Nephrologist & Consultant Urologist",
    experience: "",
    branch: "",
    image: "/doctors/dr-sibasish-mukherjee.png",
  },
  {
    id: 4,
    name: "Dr. Sudipto Chakraborty",
    qualification: "MBBS, DNB (Medicine), DrNB (Nephrology)",
    speciality: "Nephrologist, Consultant Urologist & Endocrinologist",
    experience: "",
    branch: "",
    image: "/doctors/dr-sudipto-chakraborty.png",
  },
  {
    id: 5,
    name: "Dr. Saumyabrata Deb",
    qualification: "MBBS, DNB (Medicine)",
    speciality: "General Medicine & Arthritis",
    experience: "",
    branch: "",
    image: "/doctors/dr-saumyabrata-deb.jpeg",
  },
  {
    id: 6,
    name: "Dr. Md Mehbub Alam",
    qualification: "MBBS, MS (Gyn & Obs)",
    speciality: "Obstetrics & Gynecology",
    experience: "",
    branch: "",
    image: "/doctors/dr-md-mehbub-alam.png",
  },
  {
    id: 7,
    name: "Dr. Kaleemur Rahaman",
    qualification: "MBBS, MS (Ortho), DNB, MNAMS",
    speciality: "Orthopedic, Joint Replacement & Neuro Spine Specialist",
    experience: "",
    branch: "",
    image: "/doctors/dr-kaleemur-rahaman.png",
  },
  {
    id: 8,
    name: "Dr. Akhil Xavier Josef",
    qualification: "MBBS, MS (Ortho), FISS",
    speciality: "Orthopedic, Joint Replacement & Neuro Spine Specialist",
    experience: "",
    branch: "",
    image: "/doctors/dr-akhil-xavier-josef.png",
  },
  {
    id: 9,
    name: "Dr. Lavin Gowda",
    qualification: "MBBS, MD (Internal Medicine)",
    speciality: "Medical Gastroenterologist & Diabetologist",
    experience: "",
    branch: "",
    image: "/doctors/dr-lavin-gowda.png",
  },
];